---

# For general config, see sample-config.yml

bots:
  - name: sample-normal-bot
    # plus other config values
    strategy: normal
    strategyDetails:
      expectedMarkPrice: 0
      auctionVolume: 0
      maxLong: 0
      maxShort: 0
      posManagementFraction: 0.0
      stakeFraction: 0.0
      ordersFraction: 0.0
      shorteningShape: 'TBD, json or yaml'
      longeningShape: 'TBD, json or yaml'
      posManagementSleepMilliseconds: 1234
      marketPriceSteeringRatePerSecond: 0.1
      limitOrderDistributionParams: 'TBD, json or yaml'
      targetLNVol: 0.0
