---

server:
  env: prod  # dev, prod
  listen: ":7800"
  logformat: json_pretty  # json, text
  loglevel: debug  # debug, info, warning, error

callTimeoutMills: 10000
vegaAssetID: b4f2726571fbe8e33b442dc92ed2d7f0d810e21835b7371a7915a365f07ccd9b

pricing:
  address:
    scheme: https
    host: prices.ops.vega.xyz
    path: /prices
wallet:
  url: http://localhost:1789
token:
  ethereumAPIAddress:   ws://localhost:8545
  erc20BridgeAddress:   0x9708FF7510D4A7B9541e1699d15b53Ecb1AFDc54
  stakingBridgeAddress: 0x9135f5afd6F055e731bca2348429482eE614CFfA
  syncTimeoutSec: 100
whale:
  walletName: whale
  walletPassphrase: pastazazube
  ownerPrivateKeys:
    993ed98f4f770d91a796faab1738551193ba45c62341d20597df70fea6704ede: a37f4c2a678aefb5037bf415a826df1540b330b7e471aa54184877ba901b9ef0
    b4f2726571fbe8e33b442dc92ed2d7f0d810e21835b7371a7915a365f07ccd9b: a37f4c2a678aefb5037bf415a826df1540b330b7e471aa54184877ba901b9ef0
  faucetURL: http://localhost:1790
  faucetRateLimit: 2s
  slack:
    appToken:
    botToken:
    channelID:
    enabled: false
locations:
  - localhost:3027
  - localhost:3017
  - localhost:3007
bots:
  - name: w00
    instrumentBase: BTC
    instrumentQuote: USD
    quoteAssetID: 993ed98f4f770d91a796faab1738551193ba45c62341d20597df70fea6704ede # 0x3773A5c7aFF77e014cBF067dd31801b4C6dc4136
    settlementAssetID: 993ed98f4f770d91a796faab1738551193ba45c62341d20597df70fea6704ede
    strategy: normal
    strategyDetails:
      auctionVolume: 100
      maxLong: 100
      maxShort: 100
      posManagementFraction: 0.25
      ordersFraction: 0.25
      seedAmount: 1000000000000000000
      seedOrderSize: 400
      commitmentAmount: 50000000000000
      fee: 0.01
      shorteningShape:
        sells:
          - {reference: Ask, proportion: 10, offset: 80000}
          - {reference: Ask, proportion: 20, offset: 40000}
          - {reference: Ask, proportion: 30, offset: 20000}
          - {reference: Ask, proportion: 40, offset: 10000}
        buys:
          - {reference: Bid, proportion: 40, offset: 20000}
          - {reference: Bid, proportion: 30, offset: 40000}
          - {reference: Bid, proportion: 20, offset: 80000}
          - {reference: Bid, proportion: 10, offset: 160000}
      longeningShape:
        sells:
          - {reference: Ask, proportion: 10, offset: 160000}
          - {reference: Ask, proportion: 20, offset: 80000}
          - {reference: Ask, proportion: 30, offset: 40000}
          - {reference: Ask, proportion: 40, offset: 20000}
        buys:
          - {reference: Bid, proportion: 40, offset: 10000}
          - {reference: Bid, proportion: 30, offset: 20000}
          - {reference: Bid, proportion: 20, offset: 40000}
          - {reference: Bid, proportion: 10, offset: 80000}
      posManagementSleepMilliseconds: 5050
      marketPriceSteeringRatePerSecond: 0.25
      minPriceSteerFraction: 0.00005
      priceSteerOrderScale: 10.5
      limitOrderDistributionParams:
        method: "discreteThreeLevel"
        gttLengthSeconds: 60
        tgtTimeHorizonHours: 1.0
        numTicksFromMid: 5
        numIdenticalBots: 1
      targetLNVol: 0.25
