name: "Continous Deployment Workflow"
"on":
#   release:
#     types: [published]
  push:
    branches:
      - main
jobs:
  get-current-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"
        id: set_tag
  commit-k8s:
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.VEGA_CI_SSH_KEY }}
      - uses: actions/checkout@v3
        with:
          repository: git@github.com:vegaprotocol/k8s.git
          ref: main
      - run: |
          echo "${{ steps.set_tag.outputs.tag }}" > charts/apps/liqbot/versions/devnet
          git config --global user.name 'vega-ci-bot'
          git config --global user.email 'dev@vega.xyz'
          git commit -am "Automated version update"
          git push
