# FILE IS AUTOMATICALLY MANAGED BY github.com/vegaprotocol/terraform//github
name: "Continous Deployment Workflow"
"on":
  
  push:
    tags:
      - v*
  
jobs:
  #integration:
  #  uses: ./.github/workflows/continous-integration.yml
  delivery:
    #needs: integration
    uses: ./.github/workflows/continous-delivery.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  update-manifest-repo:
    needs: delivery
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.VEGA_CI_SSH_KEY }}
      - run: |
          
          version=$(git describe --tags --abbrev=0)
          
          git config --global user.name 'vega-ci-bot'
          git config --global user.email 'dev@vega.xyz'
          git clone git@github.com:vegaprotocol/k8s.git
                    
          echo -n "$version" > k8s/charts/apps/liqbot/stagnet2/VERSION
          
                    (
            cd k8s
            git add -A
            git commit -m "Automated version update for liqbot: $version, from repository: $GITHUB_REPOSITORY"
            git pull --rebase
            git push
          )
