# FILE IS AUTOMATICALLY MANAGED BY github.com/vegaprotocol/terraform//github
name: "Continous Deployment Workflow"
"on":
  release:
    types: [published]
jobs:
  update-manifest-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.VEGA_CI_SSH_KEY }}
      - run: |
          version=$(git describe --tags --abbrev=0)
          git config --global user.name 'vega-ci-bot'
          git config --global user.email 'dev@vega.xyz'
          git clone git@github.com:vegaprotocol/k8s.git
          cd k8s
                    echo -n "$version" > charts/apps/liqbot/devnet/VERSION
                    git add -A
          git commit -m "Automated version update for liqbot: $version, from repository: $GITHUB_REPOSITORY"
          git pull --rebase
          git push
