---

name: Release

"on":
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'  # Push events to matching v*, e.g. v1.0, v20.15.10

jobs:

  release:
    name: Release on ${{ matrix.os }} with Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ['1.16']
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: make deps

      - name: Tests
        run: make test

      - name: Lint
        run: |
          if ! command -v golint 1>/dev/null ; then
            go get golang.org/x/lint/golint@latest || exit 1
          fi
          make lint
        if: ${{ matrix.os != 'windows-latest' }}

      - name: Vet
        run: make vet

      - name: Set release version
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Build
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: make release-${{ matrix.os }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
